python .\main.py -d 4 -o 4d-exp0
python .\main.py -d 4 -o 4d-exp1
python .\main.py -d 4 -o 4d-exp2
python .\main.py -d 4 -o 4d-exp3
python .\main.py -d 4 -o 4d-exp4
python .\main.py -d 4 -o 4d-exp5
python .\main.py -d 4 -o 4d-exp6
python .\main.py -d 4 -o 4d-exp7
python .\main.py -d 4 -o 4d-exp8
python .\main.py -d 4 -o 4d-exp9